version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: atlas-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
    restart: unless-stopped

volumes:
  mongo_data:
  mongo_configdb: